"""
This script fetches the top 10 trends from Twitter.
"""

import os
import yaml
import openai
import tweepy
import datetime
import requests
from tweepy import OAuthHandler

# Create a folder with current month if not exist
# the one of which is within the folder of current year
month = datetime.datetime.now().month
if not os.path.exists(str(month)):
    os.makedirs(str(month))

# Create a folder with current day if not exist
# the one of which is within the folder of current month
day = datetime.datetime.now().day
root = str(month) + '/' + str(day)
if not os.path.exists(root):
    os.makedirs(root)

# Set up Twitter API
with open('../twitter.yaml', 'r') as f:
    config = yaml.safe_load(f.read())
auth = OAuthHandler(config['consumer_key'], config['consumer_secret'])
auth.set_access_token(config['access_token'], config['access_token_secret'])
api = tweepy.API(auth)

# Get trends from tweepy
trends = api.get_place_trends(1)[0]['trends']

# Create a text file with current day if not exist
# the one of which is within the folder of current month.
# Happend "trends" to the file name.

f = open(root + '/trends.txt', 'w+')
# Write the 10 trends to the file
for trend in trends[:10]:
    f.write(trend['name'] + '\n')
f.close()

with open('../openai.yaml', 'r') as f:
    config = yaml.safe_load(f.read())

openai.organization = config['organization']
openai.api_key = config['api_key']

# Generate an image from the 10 trends
# using the GPT-3 API from OpenAI

for idx, trend in enumerate(trends[:10]):
    prompt = "Write a daily news front-page column based on the following trend\" " + trend['name'] + " \""

    response = openai.Completion.create(
        engine="text-davinci-002",
        prompt=prompt,
        temperature=0.8,
        max_tokens=256,
        top_p=1,
        frequency_penalty=0.05,
        presence_penalty=0.05,
    )
    
    print('---------------')
    print(trend['name'])
    print(response['choices'][0]['text'])
    
    f = open(root + '/{}.txt'.format(idx), 'w+')
    f.write(response['choices'][0]['text'] + '\n')
    f.close()

    # Create a PNG file with the name of the trend
    # by using the text generated by Dall-e
    # the one of which is within the folder of current day.

    image = openai.Image.create(
                prompt=trend['name'],
                n=2,
                size="1024x1024"
            )

    # get image url
    image_url = image['data'][0]['url']

    # download image
    image_data = requests.get(image_url).content
    

    # save image as png
    with open(root + '/trend_' + str(idx) + '.png', 'wb') as handler:
        handler.write(image_data)

